// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcTb_CnrFbIk3w3smLShXc_nM4seFTS_Q',
    appId: '1:827060067308:web:01bb248ae026bdfff23ec9',
    messagingSenderId: '827060067308',
    projectId: 'atchounin-b0e38',
    authDomain: 'atchounin-b0e38.firebaseapp.com',
    databaseURL: 'https://atchounin-b0e38-default-rtdb.firebaseio.com',
    storageBucket: 'atchounin-b0e38.appspot.com',
    measurementId: 'G-CYQ5FSTX5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVI5n88KhRmCY_v32C_iMKuH93SLFGDRo',
    appId: '1:827060067308:android:b23dd3ebf103d95cf23ec9',
    messagingSenderId: '827060067308',
    projectId: 'atchounin-b0e38',
    databaseURL: 'https://atchounin-b0e38-default-rtdb.firebaseio.com',
    storageBucket: 'atchounin-b0e38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU-3WKBccX0wbSyeiYNwCU2_d7qpd_tcY',
    appId: '1:827060067308:ios:3d21d9f3a901c782f23ec9',
    messagingSenderId: '827060067308',
    projectId: 'atchounin-b0e38',
    databaseURL: 'https://atchounin-b0e38-default-rtdb.firebaseio.com',
    storageBucket: 'atchounin-b0e38.appspot.com',
    androidClientId: '827060067308-bjmt59ii82gsecjbnlks9fsug95jrlsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.wecodeByChat',
  );

}